name: ci

on:
  push:
    paths:
      - "**.py"

jobs:

  strategy:
    matrix:
      os: [ubuntu-latest, windows-latest, macos-latest]

  core:

    runs-on: ${{ matrix.os }}

    steps:

    - name: "astrometry.net (Linux)"
      if: runner.os == 'Linux'
      run: sudo apt install --no-install-recommends astrometry.net astrometry-data-tycho2-10-19

    - name: "astrometry.net (macOS)"
      if: runner.os == 'macOS'
      run: brew install astrometry-net

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - run: pytest
