name: ci

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/ci.yml"

jobs:


  core:

    strategy:
      matrix:
        os: [ubuntu-latest]
        use_pymap: [true, false]


    runs-on: ${{ matrix.os }}

    steps:

    - name: "astrometry.net (Linux)"
      if: runner.os == 'Linux'
      run: sudo apt install --no-install-recommends astrometry.net astrometry-data-tycho2-10-19

    - name: "astrometry.net (macOS)"
    # FIXME: would also need data installed
      if: runner.os == 'macOS'
      run: brew install astrometry-net
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - run: pip install .[tests,lint]

    - run: pip install pymap3d
      if: ${{ matrix.use_pymap }}

    - run: flake8
    - run: mypy

    - run: pytest
