name: ci

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/ci.yml"

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1


jobs:

  core:

    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: ['3.9', '3.12']

    runs-on: ${{ matrix.os }}

    steps:

    - name: "astrometry.net (Linux)"
      if: runner.os == 'Linux'
      run: sudo apt install --no-install-recommends astrometry.net astrometry-data-tycho2-10-19

    - name: "astrometry.net (macOS)"
    # FIXME: would also need data installed
      if: runner.os == 'macOS'
      run: brew install astrometry-net

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - run: pytest
